version: 2

seeds:
  - name: lkp_divisions
    config:
      schema: {{env_var('DBT_LKP_SCHEMA','lookup')}}
  
  - name: lkp_categories
    config:
      schema: {{env_var('DBT_LKP_SCHEMA','lookup')}}

  - name: lkp_shippers
    config:
      schema: {{env_var('DBT_LKP_SCHEMA','lookup')}}